using System.Text;

namespace MindedOS.Ai;

/// <summary>Musical parameters for a song, derived from the EEG session.</summary>
public sealed record SongParams(
    string Title,
    string Author,
    string Copyright,
    int Tempo,        // FamiTracker tempo (BPM-ish)
    int Speed,        // ticks/row (lower = faster)
    bool Minor,       // tense/army -> minor; calm -> brighter
    int Density,      // 0..2 melodic/drum busyness
    int Seed,         // stable seed from the EEG word stream
    int Reps);        // arrangement repeats (~song length)

/// <summary>
/// Deterministic FamiTracker text-export song generator (VRC6, 8 channels),
/// ported from the project's gen_song.py whose grammar comes straight from
/// Source/TextExporter.cpp. Given EEG-derived <see cref="SongParams"/> it always
/// emits a valid file importable via FamiTracker ▸ File ▸ Import Text.
/// </summary>
public static class FamiTrackerSong
{
    private const int Rows = 64;   // rows per pattern
    private const int Block = 16;  // rows per chord (4 chords/pattern)
    private const int Nch = 8;     // VRC6 channel count

    // instrument indices
    private const int ILead = 0, IHarm = 1, IBass = 2, IDrum = 3, IVPulse = 4, IVSaw = 5;

    private static readonly Dictionary<string, string[]> Triad = new()
    {
        ["Am"] = new[] { "A-4", "C-5", "E-5" },
        ["F"]  = new[] { "F-4", "A-4", "C-5" },
        ["C"]  = new[] { "C-5", "E-5", "G-5" },
        ["G"]  = new[] { "G-4", "B-4", "D-5" },
        ["Dm"] = new[] { "D-4", "F-4", "A-4" },
        ["E"]  = new[] { "E-4", "G#4", "B-4" },
    };
    private static readonly Dictionary<string, string> BassRoot = new()
    {
        ["Am"] = "A", ["F"] = "F", ["C"] = "C", ["G"] = "G", ["Dm"] = "D", ["E"] = "E",
    };

    // chord progression per pattern (0 intro, 1 verse, 2 chorus, 3 bridge)
    private static readonly Dictionary<int, string[]> ProgMinor = new()
    {
        [0] = new[] { "Am", "F", "C", "G" },
        [1] = new[] { "Am", "F", "C", "G" },
        [2] = new[] { "C", "G", "Am", "F" },
        [3] = new[] { "Am", "G", "F", "E" },
    };
    private static readonly Dictionary<int, string[]> ProgBright = new()
    {
        [0] = new[] { "C", "G", "Am", "F" },
        [1] = new[] { "C", "G", "Am", "F" },
        [2] = new[] { "F", "C", "G", "Am" },
        [3] = new[] { "C", "G", "F", "G" },
    };

    private const string Empty = "... .. . ...";

    // ---- cell helpers -----------------------------------------------------
    private static string Cell(string? note, int? inst = null, int? vol = null, string eff = "...")
    {
        string n = note ?? "...";
        string i = inst is { } iv ? iv.ToString("X2") : "..";
        string v = vol is { } vv ? vv.ToString("X") : ".";
        return $"{n} {i} {v} {eff}";
    }
    private static string Noise(int v) => $"{v:X}-#";

    // ---- public API -------------------------------------------------------

    public static string Render(SongParams p)
    {
        var prog = p.Minor ? ProgMinor : ProgBright;
        var rng = new Lcg(p.Seed);

        var L = new List<string>();
        void W(string s) => L.Add(s);

        W("# FamiTracker text export 0.4.2");
        W("");
        W("# Song information");
        W($"TITLE           \"{Sanitize(p.Title)}\"");
        W($"AUTHOR          \"{Sanitize(p.Author)}\"");
        W($"COPYRIGHT       \"{Sanitize(p.Copyright)}\"");
        W("");
        W("# Song comment");
        W("COMMENT \"Generated by mindedOS from 3 min of EEG. Import: File > Import text.\"");
        W("");
        W("# Global settings");
        W("MACHINE         0");
        W("FRAMERATE       0");
        W("EXPANSION       1");
        W("VIBRATO         1");
        W("SPLIT           32");
        W("");
        W("# Macros");
        W("MACRO       0   0  -1  -1   0 : 15 15 14 13 12 12 11 11 10 10");
        W("MACRO       0   1  -1  -1   0 : 13 12 11 10 10 9 9 8");
        W("MACRO       0   2  -1  -1   0 : 15 12 8 5 2 0");
        W("MACRO       4   0  -1  -1   0 : 2");
        W("MACRO       4   1  -1  -1   0 : 0");
        W("MACROVRC6   0   0  -1  -1   0 : 14 13 12 12 11 11 10 10");
        W("MACROVRC6   4   0  -1  -1   0 : 7");
        W("");
        W("# DPCM samples");
        W("");
        W("# Instruments");
        W("INST2A03   0    0  -1  -1  -1   0 \"Lead\"");
        W("INST2A03   1    1  -1  -1  -1   1 \"Harmony\"");
        W("INST2A03   2   -1  -1  -1  -1  -1 \"Bass Tri\"");
        W("INST2A03   3    2  -1  -1  -1  -1 \"Drums\"");
        W("INSTVRC6   4    0  -1  -1  -1   0 \"VRC6 Pulse\"");
        W("INSTVRC6   5    0  -1  -1  -1  -1 \"VRC6 Saw\"");
        W("");
        W("# Tracks");
        W("");
        W($"TRACK  {Rows}   {p.Speed} {p.Tempo} \"{Sanitize(p.Title)}\"");
        W("COLUMNS : 1 1 1 1 1 1 1 1");
        W("");

        var arrangement = Arrangement(p.Reps);
        for (int fr = 0; fr < arrangement.Count; fr++)
        {
            int pat = arrangement[fr];
            var cells = string.Join(" ", Enumerable.Repeat(pat.ToString("X2"), Nch));
            W($"ORDER {fr:X2} : {cells}");
        }
        W("");

        for (int pat = 0; pat < 4; pat++)
        {
            W($"PATTERN {pat:X2}");
            foreach (var line in BuildPattern(pat, prog, p, rng)) W(line);
            W("");
        }
        W("# End of export");
        W("");

        var text = string.Join("\n", L);
        Validate(L);
        return text;
    }

    /// <summary>Derive song parameters from the EEG session averages + word stream.</summary>
    public static SongParams FromEeg(double avgAttention, double avgMeditation,
        string dominantBandKey, IReadOnlyList<string> words, string skew = "army")
    {
        // Tense/stressed brains → minor & army; calm → brighter.
        bool minor = avgMeditation < 50 || dominantBandKey is "highBeta" or "lowBeta";
        int tempo = (int)Math.Clamp(110 + avgAttention * 0.8, 110, 190);
        int density = avgAttention > 66 ? 2 : avgAttention > 33 ? 1 : 0;
        int reps = avgAttention > 50 ? 4 : 3;
        int seed = StableHash(words);
        string title = MakeTitle(words, seed, skew);
        return new SongParams(title, "mindedOS BCI", DateTime.Now.Year.ToString(),
            tempo, 6, minor, density, seed, reps);
    }

    // ---- arrangement ------------------------------------------------------
    private static List<int> Arrangement(int reps)
    {
        var list = new List<int> { 0 };
        for (int i = 0; i < Math.Max(1, reps); i++)
            list.AddRange(new[] { 1, 1, 2, 2, 1, 3, 2, 2 });
        list.AddRange(new[] { 1, 2, 3, 2 });
        return list;
    }

    // ---- pattern assembly -------------------------------------------------
    private static IEnumerable<string> BuildPattern(int pat, Dictionary<int, string[]> prog, SongParams p, Lcg rng)
    {
        var cols = new List<string[]>
        {
            ChLead(pat, prog, p, rng),
            ChHarm(pat, prog, p),
            ChBass(pat, prog),
            ChDrums(pat, p),
            ChEmpty(),                 // DPCM
            ChArp(pat, prog),
            ChPad(pat, prog),
            ChSaw(pat, prog),
        };
        for (int r = 0; r < Rows; r++)
        {
            var rowCells = new string[Nch];
            for (int c = 0; c < Nch; c++) rowCells[c] = cols[c][r];
            yield return $"ROW {r:X2} : " + string.Join(" : ", rowCells);
        }
    }

    private static string[] ChEmpty()
    {
        var a = new string[Rows];
        Array.Fill(a, Empty);
        return a;
    }

    private static string[] ChLead(int pat, Dictionary<int, string[]> prog, SongParams p, Lcg rng)
    {
        var outp = new List<string>();
        foreach (var chord in prog[pat])
        {
            var tri = Triad[chord];
            // place a note every 2 rows (8 per block); rests scale down with density
            for (int k = 0; k < Block; k++)
            {
                bool onBeat = k % 2 == 0;
                bool play = onBeat && (p.Density >= 1 || k % 4 == 0) && !(pat == 0 && k % 4 != 0);
                if (play && rng.Next(0, 10) < 8)
                    outp.Add(Cell(tri[rng.Next(0, 3)], ILead));
                else
                    outp.Add(Empty);
            }
        }
        return outp.ToArray();
    }

    private static string[] ChHarm(int pat, Dictionary<int, string[]> prog, SongParams p)
    {
        var outp = new List<string>();
        bool rest = pat == 3; // bridge harmony rests
        foreach (var chord in prog[pat])
        {
            var tri = Triad[chord];
            for (int k = 0; k < Block; k++)
            {
                if (!rest && k % 2 == 0 && p.Density >= 1)
                    outp.Add(Cell(tri[(k / 2) % 3], IHarm, 0xB));
                else
                    outp.Add(Empty);
            }
        }
        return outp.ToArray();
    }

    private static string[] ChBass(int pat, Dictionary<int, string[]> prog)
    {
        var outp = new List<string>();
        foreach (var chord in prog[pat])
        {
            var r = BassRoot[chord];
            for (int k = 0; k < Block; k++)
            {
                if (k % 4 == 0) outp.Add(Cell($"{r}-2", IBass));
                else if (k % 4 == 2) outp.Add(Cell($"{r}-3", IBass));
                else outp.Add(Empty);
            }
        }
        return outp.ToArray();
    }

    private static string[] ChArp(int pat, Dictionary<int, string[]> prog)
    {
        var outp = new List<string>();
        bool soft = pat == 0;
        foreach (var chord in prog[pat])
        {
            var tri = Triad[chord];
            for (int k = 0; k < Block; k++)
                outp.Add(Cell(tri[k % 3], IVPulse, soft ? 0x7 : null));
        }
        return outp.ToArray();
    }

    private static string[] ChPad(int pat, Dictionary<int, string[]> prog)
    {
        var outp = new List<string>();
        foreach (var chord in prog[pat])
        {
            var top = Triad[chord][2];
            for (int k = 0; k < Block; k++)
                outp.Add(k is 0 or 8 ? Cell(top, IVPulse, 0x8) : Empty);
        }
        return outp.ToArray();
    }

    private static string[] ChSaw(int pat, Dictionary<int, string[]> prog)
    {
        var outp = new List<string>();
        foreach (var chord in prog[pat])
        {
            var r = BassRoot[chord];
            for (int k = 0; k < Block; k++)
                outp.Add(k % 4 == 0 ? Cell($"{r}-3", IVSaw, 0xC) : Empty);
        }
        return outp.ToArray();
    }

    private static string[] ChDrums(int pat, SongParams p)
    {
        if (pat == 0) return ChEmpty(); // intro: no drums
        bool busy = pat == 2 || p.Density >= 2;
        var outp = new List<string>();
        for (int blk = 0; blk < 4; blk++)
        {
            var info = new Dictionary<int, (string n, int v)>();
            foreach (var k in new[] { 0, 8 }) info[k] = (Noise(0xE), 0xF);     // kick
            foreach (var k in new[] { 4, 12 }) info[k] = (Noise(0x8), 0xC);    // snare
            foreach (var k in new[] { 2, 6, 10, 14 }) info[k] = (Noise(0x1), 0x5); // hat
            if (busy) foreach (var k in new[] { 7, 15 }) info[k] = (Noise(0x1), 0x4);
            for (int k = 0; k < Block; k++)
                outp.Add(info.TryGetValue(k, out var d) ? Cell(d.n, IDrum, d.v) : Empty);
        }
        return outp.ToArray();
    }

    // ---- helpers ----------------------------------------------------------
    private static string Sanitize(string s) => s.Replace('"', '\'').Replace('\n', ' ').Trim();

    private static int StableHash(IReadOnlyList<string> words)
    {
        // FNV-1a over the joined words — deterministic across runs/processes.
        unchecked
        {
            uint h = 2166136261;
            foreach (var ch in string.Join(' ', words))
            {
                h ^= ch;
                h *= 16777619;
            }
            return (int)(h & 0x7FFFFFFF);
        }
    }

    private static string MakeTitle(IReadOnlyList<string> words, int seed, string skew)
    {
        var prefix = string.Equals(skew, "army", StringComparison.OrdinalIgnoreCase) ? "Operation " : "";
        var pick = words.Where(w => w.Length >= 4).Distinct().Take(40).ToList();
        if (pick.Count == 0) return prefix + "Brainwave March";
        var rng = new Lcg(seed);
        string a = Title(pick[rng.Next(0, pick.Count)]);
        string b = pick.Count > 1 ? Title(pick[rng.Next(0, pick.Count)]) : "March";
        return $"{prefix}{a} {b}";
    }

    private static string Title(string w) =>
        w.Length == 0 ? w : char.ToUpperInvariant(w[0]) + w[1..].ToLowerInvariant();

    /// <summary>Mirror gen_song.py's self-check: every ROW must be 8 well-formed cells.</summary>
    public static void Validate(IReadOnlyList<string> lines)
    {
        foreach (var ln in lines)
        {
            if (!ln.StartsWith("ROW ", StringComparison.Ordinal)) continue;
            var body = ln.Split(" : ", 2)[1];
            var parts = body.Split(" : ");
            if (parts.Length != Nch)
                throw new InvalidOperationException($"row has {parts.Length} cells: {ln}");
            foreach (var cell in parts)
            {
                var toks = cell.Split(' ');
                if (toks.Length != 4 || toks[0].Length != 3 || toks[1].Length != 2 || toks[3].Length != 3)
                    throw new InvalidOperationException($"bad cell '{cell}' in: {ln}");
            }
        }
    }

    /// <summary>Tiny deterministic LCG so seeded choices are reproducible.</summary>
    private sealed class Lcg
    {
        private uint _state;
        public Lcg(int seed) => _state = (uint)seed == 0 ? 1u : (uint)seed;
        public int Next(int minInclusive, int maxExclusive)
        {
            _state = _state * 1664525 + 1013904223;
            int span = maxExclusive - minInclusive;
            return minInclusive + (int)(_state % (uint)span);
        }
    }
}
